#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  Aug 23, 2022 11:20:22 PM AEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m46" -background #3e3e3e \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1133x816+440+78
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 2141
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "GUI" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m46 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background #c0c0c0 -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    ttk::progressbar $top.tPr50 \
        -length 197 
    vTcl:DefineAlias "$top.tPr50" "TProgressbar1" vTcl:WidgetProc "GUI" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #3e3e3e \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Motion Progress} 
    vTcl:DefineAlias "$top.lab47" "Label1" vTcl:WidgetProc "GUI" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -borderwidth 10 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 36 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text ESTOP 
    vTcl:DefineAlias "$top.but48" "ESTOP" vTcl:WidgetProc "GUI" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff8040 -borderwidth 5 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Reset 
    vTcl:DefineAlias "$top.but46" "RESET" vTcl:WidgetProc "GUI" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #00b300 -borderwidth 5 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text {Cycle Start} 
    vTcl:DefineAlias "$top.but47" "CYCLESTART" vTcl:WidgetProc "GUI" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -borderwidth 5 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Shutdown 
    vTcl:DefineAlias "$top.but49" "SHUTDOWN" vTcl:WidgetProc "GUI" 1
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -borderwidth 5 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground #ffffff \
        -highlightcolor black -pady 0 -text {Feed Hold} 
    vTcl:DefineAlias "$top.but50" "FEEDHOLD" vTcl:WidgetProc "GUI" 1
    frame $top.fra46 \
        -borderwidth 5 -relief raised -background $vTcl(actual_gui_bg) \
        -height 128 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 191 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "GUI" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background #000000 -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #00ff00 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -justify left -text {{}} 
    vTcl:DefineAlias "$site_3_0.lab49" "STATUSMESSAGE" vTcl:WidgetProc "GUI" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.89 -height 0 -relheight 0.68 -anchor nw \
        -bordermode ignore 
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(complement_color)]
    ttk::notebook $top.tNo51 \
        -width 529 -height 496 -takefocus {} 
    vTcl:DefineAlias "$top.tNo51" "TNotebook1" vTcl:WidgetProc "GUI" 1
    frame $top.tNo51.t0 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo51.t0" "TNotebook1_t1" vTcl:WidgetProc "GUI" 1
    $top.tNo51 add $top.tNo51.t0 \
        -padding 0 -sticky nsew -state normal -text Position -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo51.t0
    label $site_4_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background #ffffff -borderwidth 0.5 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief solid \
        -text {Actuator Control: Position Control (position commands supplied to motor)
Vibration Control: PID} \
        -wraplength 284 
    vTcl:DefineAlias "$site_4_0.lab70" "Label2" vTcl:WidgetProc "GUI" 1
    ttk::scale $site_4_0.tSc74 \
        -length 175 -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tSc74" "TScale1" vTcl:WidgetProc "GUI" 1
    label $site_4_0.lab75 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Motor Parameters} 
    vTcl:DefineAlias "$site_4_0.lab75" "Label3" vTcl:WidgetProc "GUI" 1
    label $site_4_0.lab76 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Kp 
    vTcl:DefineAlias "$site_4_0.lab76" "Label3_1" vTcl:WidgetProc "GUI" 1
    label $site_4_0.lab77 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Ki 
    vTcl:DefineAlias "$site_4_0.lab77" "Label3_1_1" vTcl:WidgetProc "GUI" 1
    label $site_4_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Kd 
    vTcl:DefineAlias "$site_4_0.lab78" "Label3_1_1_1" vTcl:WidgetProc "GUI" 1
    place $site_4_0.lab70 \
        -in $site_4_0 -x 0 -relx 0.033 -y 0 -rely 0.05 -width 0 \
        -relwidth 0.913 -height 0 -relheight 0.15 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tSc74 \
        -in $site_4_0 -x 0 -relx 0.438 -y 0 -rely 0.302 -width 0 \
        -relwidth 0.333 -height 82 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab75 \
        -in $site_4_0 -x 0 -relx 0.057 -y 0 -rely 0.27 -width 0 \
        -relwidth 0.217 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab76 \
        -in $site_4_0 -x 0 -relx 0.057 -y 0 -rely 0.317 -width 0 \
        -relwidth 0.065 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab77 \
        -in $site_4_0 -x 0 -relx 0.057 -y 0 -rely 0.365 -width 0 \
        -relwidth 0.046 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab78 \
        -in $site_4_0 -x 0 -relx 0.057 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.046 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    frame $top.tNo51.t1 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo51.t1" "TNotebook1_t2" vTcl:WidgetProc "GUI" 1
    $top.tNo51 add $top.tNo51.t1 \
        -padding 0 -sticky nsew -state normal -text Velocity -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo51.t1
    label $site_4_1.lab71 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background #ffffff -borderwidth 0.5 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief solid \
        -text {Actuator Control: Velocity Control (velocity commands supplied to motor)

Vibration Control: PID} \
        -wraplength 284 
    vTcl:DefineAlias "$site_4_1.lab71" "Label2_1" vTcl:WidgetProc "GUI" 1
    place $site_4_1.lab71 \
        -in $site_4_1 -x 0 -relx 0.033 -y 0 -rely 0.1 -width 0 \
        -relwidth 0.913 -height 0 -relheight 0.455 -anchor nw \
        -bordermode ignore 
    frame $top.tNo51.t2 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo51.t2" "TNotebook1_t3" vTcl:WidgetProc "GUI" 1
    $top.tNo51 add $top.tNo51.t2 \
        -padding 0 -sticky nsew -state normal -text Torque -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo51.t2
    label $site_4_2.lab72 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background #ffffff -borderwidth 0.5 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief solid \
        -text {Actuator Control: Torque Control (electrical current commands supplied to motor)

Vibration Control: PID
} \
        -wraplength 284 
    vTcl:DefineAlias "$site_4_2.lab72" "Label2_1_1" vTcl:WidgetProc "GUI" 1
    place $site_4_2.lab72 \
        -in $site_4_2 -x 0 -relx 0.033 -y 0 -rely 0.05 -width 0 \
        -relwidth 0.947 -height 0 -relheight 0.455 -anchor nw \
        -bordermode ignore 
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton $top.tRa60 \
        -variable mode -text Position -compound left 
    vTcl:DefineAlias "$top.tRa60" "POSITION" vTcl:WidgetProc "GUI" 1
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton $top.tRa62 \
        -variable mode -value 2 -text Velocity -compound left 
    vTcl:DefineAlias "$top.tRa62" "VELOCITY" vTcl:WidgetProc "GUI" 1
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton $top.tRa63 \
        -variable mode -value 3 -text Torque -compound left 
    vTcl:DefineAlias "$top.tRa63" "TORQUE" vTcl:WidgetProc "GUI" 1
    label $top.lab64 \
        -activebackground #f9f9f9 -activeforeground black -background #3e3e3e \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Actuator Internal Control Mode} 
    vTcl:DefineAlias "$top.lab64" "Label1_1" vTcl:WidgetProc "GUI" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $top.tCh53 \
        -variable controller -takefocus {} \
        -text {Disable Vibration Controller} -compound left 
    vTcl:DefineAlias "$top.tCh53" "DISABLEVIBRATIONCONTROLLER" vTcl:WidgetProc "GUI" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPr50 \
        -in $top -x 0 -relx 0.026 -y 0 -rely 0.784 -width 0 -relwidth 0.177 \
        -height 22 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.026 -y 0 -rely 0.735 -width 0 -relwidth 0.169 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.031 -y 0 -rely 0.042 -width 197 -relwidth 0 \
        -height 104 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.132 -y 0 -rely 0.208 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.018 -y 0 -rely 0.895 -width 87 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.208 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.124 -y 0 -rely 0.895 -width 87 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.282 -width 0 -relwidth 0.169 \
        -height 0 -relheight 0.157 -anchor nw -bordermode ignore 
    place $top.tNo51 \
        -in $top -x 0 -relx 0.45 -y 0 -rely 0.355 -width 0 -relwidth 0.467 \
        -height 0 -relheight 0.608 -anchor nw -bordermode ignore 
    place $top.tRa60 \
        -in $top -x 0 -relx 0.441 -y 0 -rely 0.074 -width 0 -relwidth 0.064 \
        -height 0 -relheight 0.028 -anchor nw -bordermode ignore 
    place $top.tRa62 \
        -in $top -x 0 -relx 0.441 -y 0 -rely 0.098 -width 0 -relwidth 0.064 \
        -height 0 -relheight 0.028 -anchor nw -bordermode ignore 
    place $top.tRa63 \
        -in $top -x 0 -relx 0.441 -y 0 -rely 0.123 -width 0 -relwidth 0.064 \
        -height 0 -relheight 0.028 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.507 -y 0 -width 0 -relwidth 0.347 -height 0 \
        -relheight 0.065 -anchor nw -bordermode ignore 
    place $top.tCh53 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.502 -width 0 -relwidth 0.162 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

