#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  Aug 23, 2022 02:38:35 PM AEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m46" -background #3e3e3e \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 651x480+951+234
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 2141
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "GUI" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m46 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background #c0c0c0 -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    ttk::progressbar $top.tPr50 \
        -length 199 
    vTcl:DefineAlias "$top.tPr50" "TProgressbar1" vTcl:WidgetProc "GUI" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #3e3e3e \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Motion Progress} 
    vTcl:DefineAlias "$top.lab47" "Label1" vTcl:WidgetProc "GUI" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -borderwidth 10 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 36 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text ESTOP 
    vTcl:DefineAlias "$top.but48" "ESTOP" vTcl:WidgetProc "GUI" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff8040 -borderwidth 5 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Reset 
    vTcl:DefineAlias "$top.but46" "RESET" vTcl:WidgetProc "GUI" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #00b300 -borderwidth 5 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text {Cycle Start} 
    vTcl:DefineAlias "$top.but47" "CYCLESTART" vTcl:WidgetProc "GUI" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -borderwidth 5 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Shutdown 
    vTcl:DefineAlias "$top.but49" "SHUTDOWN" vTcl:WidgetProc "GUI" 1
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -borderwidth 5 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground #ffffff \
        -highlightcolor black -pady 0 -text {Feed Hold} 
    vTcl:DefineAlias "$top.but50" "FEEDHOLD" vTcl:WidgetProc "GUI" 1
    frame $top.fra46 \
        -borderwidth 5 -relief raised -background $vTcl(actual_gui_bg) \
        -height 75 -width 196 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "GUI" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background #000000 -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #00ff00 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -justify left -text Text 
    vTcl:DefineAlias "$site_3_0.lab49" "STATUSMESSAGE" vTcl:WidgetProc "GUI" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.051 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.888 -height 0 -relheight 0.68 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPr50 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.625 -width 0 -relwidth 0.306 \
        -height 22 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.031 -y 0 -rely 0.563 -width 0 -relwidth 0.267 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.031 -y 0 -rely 0.042 -width 197 -relwidth 0 \
        -height 104 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.215 -y 0 -rely 0.292 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.875 -width 87 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.031 -y 0 -rely 0.292 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.169 -y 0 -rely 0.875 -width 87 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -relx 0.031 -y 0 -rely 0.396 -width 0 -relwidth 0.301 \
        -height 0 -relheight 0.156 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

